from typing import List, TypedDict, Optional, Any

class AgentState(TypedDict):
    """
    The state of our agent application, tracked throughout the LangGraph workflow.

    Attributes:
        question (str): The initial user question or rewritten query.
        documents (List[str]): List of retrieved document chunks (LangChain Document objects or strings).
        generation (str): The final answer generated by the LLM.
        guardrail_status (str): The outcome of the input guardrail ('allowed' or 'blocked').
        relevance_score (str): Grade from the document grader ('yes' or 'no').
        loop_step (int): Counter for the number of query rewriting loops prevents infinite cycles.
        intent (str): Classified user intent (e.g., 'financing', 'placement', 'general').
        target_collections (List[str]): List of vector store names to search based on intent.
        datasource (str): The routing destination ('vector_store' or 'general_chat').
    """
    question: str
    documents: List[Any] 
    generation: str
    guardrail_status: str
    relevance_score: str
    loop_step: int
    intent: str
    target_collections: List[str]
    datasource: str
    cache_hit: bool
